### ISSUE TITLE
Avoid action pushing to branch automatically

### ISSUE THREAD

**Issue by MR-Addict** [vn7n24fzkq/github-profile-summary-cards#140]
**Context**

What are you trying to do and how would you want to do it differently? Is it something you currently you cannot do? Is this related to an issue/problem?

I want to push built files push to other branch **manually**, because I have other profile actions that generte static svg images. Automatically pushing feature will **merge** files pushed before.

**Alternatives**

Can you achieve the same result doing it in an alternative way? Is the alternative considerable?

When summary files generated, I can manually use other github actions push these files to destination branch together.

For example:

```yml
name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # generate snake svg image
      - name: generate snake
        uses: Platane/snk/svg-only@v2
        with:
          outputs: snake/snake.svg
          github_user_name: ${{ github.repository_owner }}
      # generate summary svg image
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      # merge generated files
      - name: merge files
        run: mkdir output & mv snake output && mv profile-3d-contrib output
      # push files to output branch
      - name: push builds to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Has the feature been requested before?**

Please provide a link to the issue.

No such request yet.

**If the feature request is approved, would you be willing to submit a PR?**

Yes / No _(Help can be provided if you need assistance submitting a PR)_

Yes, I'd like to.
