### ISSUE TITLE
[Feature request] Option to remove Github icon from Stats card

### ISSUE THREAD

**Issue by VladimirAlexiev** [vn7n24fzkq/github-profile-summary-cards#141]
**Context**

At my profile https://rawgit2.com/VladimirAlexiev/my/master/index.html
I've included several Github cards: 3 from you and 1 from https://github-readme-stats.vercel.app:
![image](https://user-images.githubusercontent.com/536250/221403426-043144c8-8f5d-434b-8821-2df5ca9b4017.png)

As you see, the last card drops to a new line because there's not enough space to show it on the same line.

I'd like to remove the Github icon (crossed-out in red).
- Unlike the piecharts, it carries no info, it just takes space
- Github is already mentioned in the first card
- If I wanted to emphasize better that these are Github stats, I could include a Heading2, rather than spending horizontal space

**Alternatives**

- If I reduce browser zoom, all 4 cards fit on the same line
- There's no way to remove the icon that carries no info

**Has the feature been requested before?**

No

**If the feature request is approved, would you be willing to submit a PR?**

I might, if you give me some pointers into reading https://github.com/vn7n24fzkq/github-profile-summary-cards/blob/main/src/cards/stats-card.ts

**Comment by MR-Addict** [comment]
I think you can do something like this to make them evenly seperate into two rows like this:

```html
<div>
  <div>
    <a href="https://github.com/VladimirAlexiev"><img src="https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=VladimirAlexiev&amp;theme=vue"></a>
    <a href="https://github.com/VladimirAlexiev"><img src="https://github-profile-summary-cards.vercel.app/api/cards/repos-per-language?username=VladimirAlexiev&amp;theme=vue"></a>
  </div>
  <div>
    <a href="https://github.com/VladimirAlexiev"><img src="https://github-profile-summary-cards.vercel.app/api/cards/stats?username=VladimirAlexiev&amp;theme=vue"></a>
    <a href="https://github.com/VladimirAlexiev"><img src="https://github-readme-stats.vercel.app/api?username=VladimirAlexiev&amp;show_icons=true&amp;disable_animations=true&amp;text_bold=false&amp;card_width=365px&amp;layout=compact&amp;custom_title=Stats2&amp;include_all_commits=true&amp;count_private=true&amp;theme=vue"></a>
  </div>
</div>
```

And if you're not using markdown to write your webiste, you can definitely add some css to position your elements like this:

```css
<style>
  .github-state{
    display: grid;
    grid-template-columns: 1fr 1fr;
  }
</style>
<div class="github-state">
    <a href="https://github.com/VladimirAlexiev"><img src="https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=VladimirAlexiev&amp;theme=vue"></a>
    <a href="https://github.com/VladimirAlexiev"><img src="https://github-profile-summary-cards.vercel.app/api/cards/repos-per-language?username=VladimirAlexiev&amp;theme=vue"></a>
    <a href="https://github.com/VladimirAlexiev"><img src="https://github-profile-summary-cards.vercel.app/api/cards/stats?username=VladimirAlexiev&amp;theme=vue"></a>
    <a href="https://github.com/VladimirAlexiev"><img src="https://github-readme-stats.vercel.app/api?username=VladimirAlexiev&amp;show_icons=true&amp;disable_animations=true&amp;text_bold=false&amp;card_width=365px&amp;layout=compact&amp;custom_title=Stats2&amp;include_all_commits=true&amp;count_private=true&amp;theme=vue"></a>
</div>
```
