### ISSUE TITLE
[BUG] Issue with .yml template code not creating GitHub workflow

### ISSUE THREAD

**Issue by sohaamir** [vn7n24fzkq/github-profile-summary-cards#179]
When using the existing template `.yml` code needed to run the workflow, no 'Run workflow' option was generated. 

Reformatting the `.yml` to the following structure below fixed the issue: 

```yaml
on:
  workflow_dispatch:
  schedule:
    # Execute at midnight every day
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARD_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
```
